### ISSUE TITLE
Try to get rid of appcompat dependency

### ISSUE THREAD

**Issue by mcomella** [mcomella/FirefoxAccounts-android#13]
It was in there by default and now the style for our `LoginActivity` relies on it. It'd be great to not force the implementing application to have more methods than they really need.

At the very least, we should make the version required more lenient so the application won't have to download two versions of the support library.

With this change, we may also need to drop the use of our support library annotations.

**Comment by Sdaswani** [comment]
Will removing appcompat change our public API?

**Comment by mcomella** [comment]
No.

**Comment by mcomella** [comment]
FYI: the support libraries make the biggest impact on our method count at 19898 methods (compared to 1681 methods in the org.mozilla code). See [the dexcount output](https://gist.github.com/mcomella/8232498011e1ef4680b841c66253351f).
