### ISSUE TITLE
Add page load timeout to WebViewLoginActivity

### ISSUE THREAD

**Issue by mcomella** [mcomella/FirefoxAccounts-android#2]
It'd provide a better user experience than forcing the user to hit back.

Due to the need to handle Activity restoration from Android, this is non-trivial: you'll need to post a message to a thread (presumably, the UiThread so we don't have to waste resources creating another one) but what happens to that Runnable/message when the Activity is recreated on rotation? How do you handle the Runnable in onPause/OnResume (or is it onStop/onStart?)? Do you remove it and re-add it?

In any case, I'd recommend encapsulating the timeout state in some composable Object rather than trying to embed it directly in the Activity code.

**Comment by Sdaswani** [comment]
So what is the current user experience? Is there any indication of a timeout? Are they prompted to hit back or is that what we expect a normal user to do when their app is stuck?

**Comment by mcomella** [comment]
The user will see the web view framed with the Android Action bar with an "up on level" button:

<img width="323" alt="screen shot 2017-05-22 at 11 09 32" src="https://cloud.githubusercontent.com/assets/759372/26322307/3e281e6a-3edf-11e7-8921-87801e6b5233.png">

And a loading spinner inside the web view. My assumption is at some point, they'll realize they've been waiting long enough and click back.

**Comment by Sdaswani** [comment]
OK. As the library gains usage, this will definitely need to be addressed.

**Comment by mcomella** [comment]
I think we should use the WebViewClient's `onPageFinished` callback to determine when the page is done loading.

Firefox-iOS listens for the equivalent of `fxaccounts:loaded` from the page but on Android, we inject the webView script in `onPageFinished` so I think there's a race condition that determines if we get that message.
