### ISSUE TITLE
Use return values instead of callbacks/delegates on blocking calls

### ISSUE THREAD

**Issue by mcomella** [mcomella/FirefoxAccounts-android#3]
For some reason, some of the sync code uses "delegates", making you think they're async, but they're actually just synchronous calls that call out to an object. These delegates unnecessarily make the code really hard to read (and make you think it's async!).

Instead, these methods should add some code to steal the return value from the delegate to.

The methods (which might get renamed by the time this is implemented) that need work are:
* `FirefoxSyncCryptoKeysAccessor.getBlocking`
* `FirefoxSyncCollectionInfoAccessor.getBlocking`
* `FirefoxSyncTokenAccessor.getBlocking` - this is super fucked up: It blocks for the request and calls the callback on a separate thread
* All the get collection calls:
  * `FirefoxSyncHistory.getBlocking`
  * `FirefoxSyncPasswords.getBlocking`
  * `FirefoxSyncBookmarks.getBlocking`

The reason the delegates might exist are:
1. To provide additional input arguments (e.g. `collectionTimeout()`). But this can be done with normal function arguments
1. To call different methods on different error cases: but this can be done by throwing different types of checked exceptions (e.g. `RequestTransportException` for the `onHandleTransportException` call).

Note that when grabbing the various exceptions from the delegate, we should be sure to preserve the type of the exceptions when we throw them.

---

A good time to rewrite this code would be when implementing #4.

**Comment by Sdaswani** [comment]
Is the API documented to note this funkiness?

**Comment by mcomella** [comment]
> Is the API documented to note this funkiness?

This is issue is only internal to our code (where it is commented), not the library's API.

And it is not documented in the existing Sync code (which is the source of the problems).
