### ISSUE TITLE
Use http library that isn't httpclientandroidlib

### ISSUE THREAD

**Issue by mcomella** [mcomella/FirefoxAccounts-android#4]
`httpclientandroidlib` is undesirable because it is:
* out-dated: has verbose, unintuitive APIs
* imported directly into our code (rather than being used as a gradle library)
* Wasn't written with Android in mind (e.g. has high method count)

But we're using it because the existing sync code wraps around it. By removing it, we win:
* simpler request code
* reduced method count

We should use the Android built-in (`HttpURLConnection`) or another library (`OkHttp`?).

Note: the existing sync code forces uses unnecessary delegates for blocking calls, convolution the code - we sure be sure to remove the delegates when we rewrite the requests (see also #3).

**Comment by Sdaswani** [comment]
I'd label this a P2, at least.

**Comment by mcomella** [comment]
FTR, Nick mentioned this:

it's big. You don't want to ship it. Using a different dep would be easy. You don't have to, and you can "trust" the HTTP/TLS configuration to work, but you'll end up bring a lot of Sync with you... 14:32 Well, maybe not that much. But enough that it won't be a clean excision. 14:32 And I gave you the excision point; you should use it :)

**Comment by mcomella** [comment]
FYI: this adds 5264 methods, compared to 19k+ of the support libraries, making #13 a bigger issue. See [the dexcount output](https://gist.github.com/mcomella/8232498011e1ef4680b841c66253351f).

fwiw, OkHttp 3.2.0 (3.8.1 is latest) has [2750 methods](http://www.methodscount.com/?lib=com.squareup.okhttp3%3Aokhttp%3A3.2.0), which is only marginally better. We could use `HTTPUrlConnection` and add no methods but that's just painful.

Instead of slicing out HTTPClientLib, we could also just try removing all unused methods and see how close we get to OkHttp.
