### ISSUE TITLE
Encrypt stored FxA account metadata (i.e. not sync)

### ISSUE THREAD

**Issue by mcomella** [mcomella/FirefoxAccounts-android#5]
This data is the user's email, uid, and FxA keys (i.e. not sync - those need to be requested for). These keys will allow a user to modify FxA account data & request Sync credentials (to then access/modify that data).

Right now, we store the data in SharedPreferences, which is unencrypted. This is acceptable (and is what Fennec on Android does) because each app's data storage is protected from one another - each app runs as its own user and an app's files are saved with the user the app runs as. However, Android storage is vulnerable to the following:
* afaik, apps on rooted devices run as root and can read any files
* An unencrypted device can have its storage mounted on any computer and read from

These could be protected against if we encrypted the data ourselves. On iOS, we use the keychain (which uses the user's pin as the decryption key) but there is no easy equivalent on Android (since it has no common key) so I opted not to implement it for v1. That being said, if we can find a key (maybe the server would provide it?), we'd probably use the [KeyStore class](https://developer.android.com/reference/java/security/KeyStore.html).

**Comment by Sdaswani** [comment]
I'm surprised Android doesn't have a similar construct as iOSes keychain. Definitely cool to defer to v2.
