### ISSUE TITLE
Cache sync account credentials

### ISSUE THREAD

**Issue by mcomella** [mcomella/FirefoxAccounts-android#6]
Through-out the login process, we request various credentials every time the library user tries to access a sync account:
* Crypto keys
* Collection info
* Sync Token

We could start caching these values, saving the user's time, battery, & data caps.

Note: this could get complicated if we can't determine when some credential expires. For example, we'll have to make a request with an out-of-date cached credential, which will fail, so we'll have to re-retrieve the keys and try the request again and, if there's a failure again, then report to the library user.

**Comment by Sdaswani** [comment]
Definitely one to address in v2 of the library.
