### ISSUE TITLE
Reminder: when we have 3+ consumers, re-evaluate API

### ISSUE THREAD

**Issue by mcomella** [mcomella/FirefoxAccounts-android#8]
I spoke to ckarlof – he mentioned that if you have 3+ consumers of an API and understand their needs, you're in an optimal position to create an API to solve whatever problems they have. I saw a similar quote in a presentation on API by Joshua Bloch where with 1 or 2 consumers, you fit your API solution too closely to their problems, rather than the general problem.

So I think when this library is used more heavily, we should re-evaluate how well we solve everyone's problems.

---

One concrete idea Chris shared about API building is that you should try to make the API as stateless as possible because it helps maintainability, debugging, & makes your code more easily testable.

One way you can do this is to return the state of the world to the API consumer in some Object (call it a "token") that they may not understand but pass back into future calls with the API – this will make it easier to test (you just mock an Object of the state you desire) rather than trying to advance the state of the system by making a series of method calls (that can change over time). Additionally, you can see the whole state object to know what's going wrong, rather than having to stop in the debugger in each component of the code to evaluate its memory state.

**Comment by Sdaswani** [comment]
Awesome advice from Chris!!!
