### ISSUE TITLE
Properly handle orphaned bookmarks

### ISSUE THREAD

**Issue by mcomella** [mcomella/FirefoxAccounts-android#9]
Bookmark records can be orphaned from corruption or because the user retrieved a partial list. In the current implementation (`FirefoxSyncBookmarks.createRootBookmarksFolder`), we add the orphaned bookmarks to the root folder. This is problematic because it does not accurately represent the user's bookmarks and it can change across invocations but it was the simplest to implement to start and requires no intervention from library users, so it's easy to change later.

I think the proper solution (which this issue is for) is to download the specified number of records and then make additional requests to download any missing parent folders (and to do so until all folders are found or some unreasonable number of requests is made). This solves the problems above: the user's bookmarks are accurately represented (to the specified number) and the results will not change for that bookmark set. However, it introduces new problems: there are additional requests and thus more failure points, it can get significantly more records than specified by the library user, and it's more complicated.

**Comment by Sdaswani** [comment]
Agree let's punt to v2.

**Comment by mcomella** [comment]
> Bookmark records can be orphaned from corruption or because the user retrieved a partial list. In the current implementation (FirefoxSyncBookmarks.createRootBookmarksFolder), we add the orphaned bookmarks to the root folder.

fwiw, a better temporary solution might add the new bookmarks to a subfolder like, "Orphaned bookmarks" because it turns out the root bookmarks folder on desktop can only contain folders & not bookmarks.
